services:
  customer_db:
    image: mysql:8.0.31
    container_name: customer_db
    volumes:
      - dbbase:/var/lib/mysql
    ports:
      - "33070:3306"
    environment:
      MYSQL_ROOT_PASSWORD: bp1234
      MYSQL_DATABASE: customer_db


volumes:
  dbbase: